# Generated by Django 4.2.7 on 2026-04-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_imagen2_producto_imagen3_producto_imagen4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_oferta',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('MAS_VENDIDO', 'Más Vendido'), ('FLASH', 'Oferta Flash'), ('LIQUIDACION', 'En Liquidación')], default='NORMAL', max_length=20),
        ),
    ]
