# Generated by Django 4.2.7 on 2026-04-18 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='recompensa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='codigo_referido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puntos_recompensa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='referido_por',
        ),
        migrations.DeleteModel(
            name='ItemPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Recompensa',
        ),
    ]
