# Generated by Django 4.2.7 on 2026-04-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_pedido_usuario_remove_recompensa_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calificacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_normal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
